name: Build & Deploy BRYX Home Page UI App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo    
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/blob-upload@v1
      with:
        # Required arguments
        azure-storage-account: bryxui
        container-name: bryx-ui-home
        file-pattern: 'build/*'
        # Optional arguments
        version-prefix: 'v'
        version-metadata: true